[cluster_manager]
id52 = "rhph9fkd9ojci57nihenc0cssm4s0pdrdhq9039u5hvt157kd3ug"
cluster_name = "test"

[machine.server1]
id52 = "oshfi58qlhmpgurjf90hmbdf1jroveu7lftm7j71oj0rkc5occkg"  
allow_from = "*"
