[cluster_manager]
id52 = "cqcrt90vo034df7ubu285jseld8dhggoj277hifna29obbqvsfr0"
cluster_name = "test"

[machine.server1]
id52 = "5h2eju32cqudb5c3gmvqhhb1mjsogbb0f988nb1rq1tvb70fp6g0"  
allow_from = "*"
