[cluster_manager]
id52 = "fctso9o9rc9pj0dg8errni36n3g9nj2m2bjqo9vcjpnlh7uiut9g"
cluster_name = "test"

[machine.server1]
id52 = "2p5g5je6ivof04l3icj8so8nkr97bp2k6pea79c72g01hk3bten0"  
allow_from = "*"
