[cluster_manager]
id52 = "jjb73kp7d1aahojm29poivl2aoor6sc1d9onla721t2a1d3qbj70"
cluster_name = "test"

[machine.server1]
id52 = "kp0uajmji5rueu3sds6g2st856n0v57rbaqpjb9uas30iic22m6g"  
allow_from = "*"
