[cluster_manager]
id52 = "jrvr8vmgac2audfm5lbidub2nmg4mqunqeqbvcom9efm9qsnho70"
cluster_name = "test"

[machine.server1]
id52 = "uhk2k3tapvgdartseosg5ptek0buhuuvpmvbqfhtin909h8d94d0"  
allow_from = "*"
