[cluster_manager]
id52 = "2vfr9io1eglu7gno175m223f4hfkgupvr4v1f2j0s67i89evdr00"
cluster_name = "test"

[machine.server1]
id52 = "njjsd10g7q4hriplt6kuffjg78nftm5jpn7snji43nghgqeoofr0"  
allow_from = "*"
