[cluster_manager]
id52 = "qkm0c2a05f6ke2qa31h85cto32hupvnnqlou0515pf2m0qgmkotg"
cluster_name = "test"

[machine.server1]
id52 = "dm3l1t9cuskovaumoqioe246k4fk6c65e4sllagt2uhsv0e2geag"  
allow_from = "*"
