[cluster_manager]
id52 = "9vodgntiud9p07smpshipbbeci08n95r35rfd85akitdiuscnkog"
cluster_name = "test"

[machine.server1]
id52 = "hf5eplnudqur0vs0kp05pjabm32jd02tgsecd15prpu9uhts2j30"  
allow_from = "*"
