[package]
name = "kulfi-utils"
version = "0.1.2"
edition.workspace = true
authors.workspace = true
description = "Kulfi utilities"
homepage.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[dependencies]
kulfi-id52 = { path = "../kulfi-id52", version = "0.1.0" }
bb8.workspace = true
bytes.workspace = true
colored.workspace = true
data-encoding.workspace = true
eyre.workspace = true
file-guard.workspace = true
futures-util.workspace = true
http-body-util.workspace = true
hyper-util.workspace = true
hyper.workspace = true
iroh.workspace = true
keyring.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
hex = "0.4"
