name: Malai SSH End-to-End Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      # Trigger on SSH-related changes
      - 'malai/src/ssh/**'
      - 'malai-cli-test-utils/**'
      - 'tests/ssh_e2e_*.rs'
      - 'malai/src/main.rs'  # CLI command changes
      - 'malai/Cargo.toml'
      - 'Cargo.toml'
      - '.github/workflows/malai-ssh-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      # Trigger on SSH-related changes
      - 'malai/src/ssh/**'
      - 'malai-cli-test-utils/**'
      - 'tests/ssh_e2e_*.rs'
      - 'malai/src/main.rs'
      - 'malai/Cargo.toml'
      - 'Cargo.toml'
      - '.github/workflows/malai-ssh-tests.yml'

jobs:
  ssh-e2e-tests:
    name: SSH End-to-End Tests
    runs-on: ubuntu-22.04
    env:
      RUST_LOG: malai=debug,fastn_p2p=debug
      CI: true
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt install libdbus-1-dev pkg-config

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # Need fastn-p2p dependencies
          submodules: false

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ssh-e2e-tests

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Run clippy on SSH modules
        run: |
          cargo clippy -p malai-cli-test-utils --all-targets -- -D warnings
          cargo clippy -p malai --all-targets -- -D warnings

      - name: Build malai binary
        run: |
          echo "🔨 Building malai binary for SSH testing..."
          cargo build --bin malai
          echo "✅ Malai binary built successfully"

      - name: Build test utilities
        run: |
          echo "🔧 Building malai-cli-test-utils..."
          cargo build -p malai-cli-test-utils
          echo "✅ Test utilities built successfully"

      - name: Run SSH basic cluster test
        id: ssh-basic
        run: |
          echo "🧪 Running basic SSH cluster test..."
          cargo test ssh_e2e_basic --verbose
        continue-on-error: true

      - name: Run SSH permission tests
        id: ssh-permissions
        run: |
          echo "🧪 Running SSH permission tests..."
          cargo test ssh_e2e_permissions --verbose
        continue-on-error: true

      - name: Run SSH multi-cluster tests
        id: ssh-multi-cluster
        run: |
          echo "🧪 Running SSH multi-cluster tests..."
          cargo test ssh_e2e_multi_cluster --verbose
        continue-on-error: true

      - name: Check SSH basic test results
        if: steps.ssh-basic.outcome != 'success'
        run: |
          echo "❌ SSH basic cluster test failed"
          exit 1

      - name: Check SSH permission test results
        if: steps.ssh-permissions.outcome != 'success'
        run: |
          echo "⚠️ SSH permission tests failed (expected during development)"
          # Don't fail the build for permission tests during development
          # exit 1

      - name: Check SSH multi-cluster test results  
        if: steps.ssh-multi-cluster.outcome != 'success'
        run: |
          echo "⚠️ SSH multi-cluster tests failed (expected during development)"
          # Don't fail the build for multi-cluster tests during development
          # exit 1

      - name: SSH Test Summary
        run: |
          echo "📊 SSH Test Results:"
          echo "   Basic Cluster: ${{ steps.ssh-basic.outcome }}"
          echo "   Permissions: ${{ steps.ssh-permissions.outcome }}"  
          echo "   Multi-Cluster: ${{ steps.ssh-multi-cluster.outcome }}"
          
          if [[ "${{ steps.ssh-basic.outcome }}" == "success" ]]; then
            echo "✅ Core SSH functionality working"
          else
            echo "❌ Core SSH functionality needs work"
          fi