name: Release kulfi-utils

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish to crates.io
        run: |
          cd kulfi-utils
          cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
          cargo publish